name: "Integration Test"

on:
  push:
    # Dependabot has no access to the secrets that this workflow requires. So we
    # skip running the workflow in branches that dependabot presumably created.
    branches-ignore:
      - "dependabot/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup Git Project"
        uses: "actions/checkout@v5"

      - name: "Setup Go Env"
        uses: "actions/setup-go@v6"
        with:
          cache: true
          go-version: "1.25.1"

      - name: "Check Go Tests"
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_REGION: "${{ secrets.AWS_REGION }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          KAYRON_ENVIRONMENT: "testing"
          KAYRON_GITHUB_TOKEN: "${{ secrets.KAYRON_GITHUB_TOKEN }}"
        run: |
          go test -tags=integration ./pkg/operator -v -race -run Test_Operator_Integration
